### ISSUE TITLE
General interface troubles (ussage gauges, sound notification, powermenu problem)

### ISSUE THREAD

**Issue by A-Committed-Dev** [ikz87/dots-2.0#33] opened 2023-02-02 00:32 UTC
Hi as you can see on the pictures i cant get the graphs to work or the cpu ussage/ temp. also the powermenu works through terminal or keybind but when using the mouse it just does nothing. am i missing something ? everthing else seems to work ok,

very nice work hope theres a solution to my problem 
![billede](https://user-images.githubusercontent.com/103140181/216201339-4c7268f9-d77d-42d8-a9fd-a11860c7f65d.png)
![billede](https://user-images.githubusercontent.com/103140181/216201379-6a630b06-0b0c-4a83-9a53-242165183e54.png)

**Comment by ikz87** [comment] 2023-02-02 05:46
Hi, thanks for trying out my dotfiles.

First I wanna say that I just pushed a [fix](https://github.com/ikz87/dots-2.0/commit/a80535d6b74208f35fad4c7834ccf3e0b92c726a) for the powermenu thing, seems like I didn't test that thoroughly. It's working now at least for me. I also made the button container have an actual size, should be easier to click.

For the temperature widget, you might need to follow this [guide](https://wiki.archlinux.org/title/lm_sensors#Setup). The widget has always worked for me out of the box when using it on brand new arch installs, but due to hardware differences It might be necessary for other users to set up `lm_sensors` first. If after following the guide the temperature widget starts working, let me know so I add a link to it to the install process in the `README.md`

The CPU widget not working is the weirdest out of the 3, the command used to fetch that info is `mpstat` from the `sysstat` package, and as far as I know, it doesn't need any further setup.
Let's see what the problem is, could you please show me the ouput of the following command?
```
mpstat 1 1
```
In theory, it should look a bit similar to this:
![image](https://user-images.githubusercontent.com/98569017/216241745-0ab04fdd-bedc-4f90-941e-d08d196deca4.png)

**Comment by ikz87** [comment] 2023-02-02 06:40
> First I wanna say that I just pushed a [fix](https://github.com/ikz87/dots-2.0/commit/a80535d6b74208f35fad4c7834ccf3e0b92c726a) for the powermenu thing, seems like I didn't test that thoroughly. It's working now at least for me. I also made the button container have an actual size, should be easier to click.

Just pushed another [fix](https://github.com/ikz87/dots-2.0/commit/7200077ea7bf7129d89f72cc4012ce49666cb03f) since the button area was still a bit slim vertically.

**Comment by A-Committed-Dev** [comment] 2023-02-02 12:16
Okay so i fixed all the problems. 

you're fix fixed the issue with the mouse and power buttons. 

for the cpu ussage  i had to change the value Average: to Middel: for some reason and because my arch install is configuered in danish i had to convert the number from 100,00% to 100.00%. which i thought was properly what you coded it to use. 

for the temperature gauge i changed the grep value to search for "

cpu" and that fixed the problem. i ran the lm_sensor config before doing this i dont know if it is nessecary. 

i think most of my problems came from using the danish langauge pack for linux instead of english but it seems to be fixed now.


![2023-02-02_13:17:09](https://user-images.githubusercontent.com/103140181/216322760-7798ff1f-a77a-4c5e-8e40-11350ddc8a9d.png)

![2023-02-02_10-54](https://user-images.githubusercontent.com/103140181/216322332-c7b01f71-8f93-4be7-bb62-7be1bd1a4c7d.png)
![2023-02-02_10-56](https://user-images.githubusercontent.com/103140181/216322336-15bad9ca-e9ce-4b50-9a26-7dea9d67a71a.png)
![2023-02-02_13-15](https://user-images.githubusercontent.com/103140181/216322339-354509e7-bb23-4920-a870-ca4c74991508.png)

**Comment by A-Committed-Dev** [comment] 2023-02-02 12:36
i have just now found another issue for me. the mute function mutes the speakers but sends the wrong notification it just sends the current volume and notifiaction i would expect it to send a notification with the empty speaker and bar you get when you just turn down the volume to 0.
![2023-02-02_13:31:16](https://user-images.githubusercontent.com/103140181/216326775-fdda2030-5d9c-4990-b110-477a51bccb5a.png)
![mute1](https://user-images.githubusercontent.com/103140181/216326783-816ffc70-3469-4359-b2f3-74724be8558e.png)

**Comment by ikz87** [comment] 2023-02-02 16:45
Glad you fixed all those other problems, and saying your arch install is in danish makes me suspect that this new issue with the notifications also has to do with the language.

What's the output of running this command after muting your speakers?
```
pactl get-sink-mute @DEFAULT_SINK@
```
For me it's just `Mute: yes`
If it's anything different to you, just edit line 67 like this:
```
if [[ `is_mute` == "<your output>" ]] ; then
```

**Comment by A-Committed-Dev** [comment] 2023-02-02 16:55
Ah yes it fixed the mute issue. 

when i run it i get the danish equivalent to yes so some of my problems is language based.  
good to know incase anybody else runs into a similair problem.

so far i really enjoy you're rice and it is a good foundation for my own rice. 
please keep up the good work 👍

**Comment by ikz87** [comment] 2023-02-02 17:16
Glad we were able to sort everything out!
Will be closing now. Feel free to open a new issue if you find any other problems :)

**Closed as completed by ikz87** 2023-02-02 17:16 UTC
