### ISSUE TITLE
Should find a more quick and intuitive way of change the wallpaper

### ISSUE THREAD

**Issue by awarewen** [ikz87/dots-2.0#35] opened 2023-02-27 02:21 UTC

**Comment by awarewen** [comment] 2023-02-27 02:35
I now use the Settings of the wallpaper is the use of custom shortcuts in `ranger` quickly change the wallpaper

  ```markdown

  # 添加一个自定义命令
  #  ～/.config/ranger/commands.py
  # _____________________________
    class set_wallpaper(Command)
        def execute(self):
            if self.arg(1):
                target_filename = self.rest(1)
            else:
                target_filename = self.fm.thisfile.path
            if not os.path.exists(target_filename):
                self.fm.notify("The given file does not exist!", bad=True)
                return
            self.fm.notify("run command: set_wallpaper " + target_filename)
            # Call an external script
            self.fm.run('~/.bscripts/wallset ' + target_filename)
  # -----------------------------------------------------------------------

  # Add a key binding for a custom command
  # ~/.config/ranger/rc.conf
  # ______________________
    map tw set_wallpaper
  # ----------------------
  ```

**Comment by ikz87** [comment] 2023-02-27 05:29
I see the value on having something like what you did, I myself did something similar for thunar.
But I don't understand the actual issue here (maybe because of the language barrier?). What you did works, right? If so, what is the issue here? Would gladly help once I understand what's wrong

**Comment by awarewen** [comment] 2023-02-28 02:22
> I see the value on having something like what you did, I myself did something similar for thunar. But I don't understand the actual issue here (maybe because of the language barrier?). What you did works, right? If so, what is the issue here? Would gladly help once I understand what's wrong

I had an idea that I could just call 'hsetroot' on the 'Ranger' command to customize the wallpaper and avoid calling external scripts, i don't know whether it's more resource intensive to call an external script or a custom command in 'Ranger' , but I'd love to hear your thoughts on how to write this custom command as a 'Ranger' plugin.I'll see if I can solve this thread tonight.

**Comment by ikz87** [comment] 2023-02-28 04:52
I see now.
I don't think there's any reason for calling external scripts to be more resource intensive so if what you wrote works, I'd advice you keep using it. I'm not too familiar with ranger after all.

Now I suppose I should give an explanation as to why you should use `wallset` instead of just `hsetroot`:
The whole rice uses a colorscheme that is extracted from your wallpaper, right? The way it is implemented is that there's a file at `~/.config/rice_assets/Images/wallpaper.png`, let's call this `wp_path`. This file is the one that always get set as the wallpaper with `hsetroot` at line 13 in `autostart`:
```
12 # Set Wallpaper
13 hsetroot -cover ~/.config/rice_assets/Images/wallpaper.png 
```

Having the wallpaper being always at the same path makes things easier to set up, since all `wpgtk` related configs just need to reference the file at `wp_path`. This is exactly what happens in the first few lines of `bspwmrc`:
```
1 #!/bin/sh                                                    
2 
3 # Set the global colorscheme (requieres wptk https://github.com/deviantfero/wpgtk)
4 wpg -R wallpaper.png 
5 wpg -s wallpaper.png
6 source "${HOME}/.cache/wal/colors.sh" 
```

Then what does `wallset` do? It literally only copies the specified file to to `wp_path` and then restarts `bspwm` as a whole, so that not only the wallpaper will change, but so will the colorscheme and all configs for programs that make use of this colorscheme system. These are literally the only lines that matter in `wallset`:
``` 
16 cp $wallpaper ~/.config/rice_assets/Images/wallpaper.png
17 bspc wm -r
```

So I guess that if you really don't wanna call an external script, you could execute the following in commands in ranger:
```
cp target_filename ~/.config/rice_assets/Images/wallpaper.png
bspc wm -r
```

Was this of help? I want to know before closing the issue :)

**Comment by awarewen** [comment] 2023-02-28 14:36
> I see now. I don't think there's any reason for calling external scripts to be more resource intensive so if what you wrote works, I'd advice you keep using it. I'm not too familiar with ranger after all.
> 
> Now I suppose I should give an explanation as to why you should use `wallset` instead of just `hsetroot`: The whole rice uses a colorscheme that is extracted from your wallpaper, right? The way it is implemented is that there's a file at `~/.config/rice_assets/Images/wallpaper.png`, let's call this `wp_path`. This file is the one that always get set as the wallpaper with `hsetroot` at line 13 in `autostart`:
> 
> ```
> 12 # Set Wallpaper
> 13 hsetroot -cover ~/.config/rice_assets/Images/wallpaper.png 
> ```
> 
> Having the wallpaper being always at the same path makes things easier to set up, since all `wpgtk` related configs just need to reference the file at `wp_path`. This is exactly what happens in the first few lines of `bspwmrc`:
> 
> ```
> 1 #!/bin/sh                                                    
> 2 
> 3 # Set the global colorscheme (requieres wptk https://github.com/deviantfero/wpgtk)
> 4 wpg -R wallpaper.png 
> 5 wpg -s wallpaper.png
> 6 source "${HOME}/.cache/wal/colors.sh" 
> ```
> 
> Then what does `wallset` do? It literally only copies the specified file to to `wp_path` and then restarts `bspwm` as a whole, so that not only the wallpaper will change, but so will the colorscheme and all configs for programs that make use of this colorscheme system. These are literally the only lines that matter in `wallset`:
> 
> ```
> 16 cp $wallpaper ~/.config/rice_assets/Images/wallpaper.png
> 17 bspc wm -r
> ```
> 
> So I guess that if you really don't wanna call an external script, you could execute the following in commands in ranger:
> 
> ```
> cp target_filename ~/.config/rice_assets/Images/wallpaper.png
> bspc wm -r
> ```
> 
> Was this of help? I want to know before closing the issue :)

Yep!! :+1:   :)) , This is a simple external call：

- `~/.config/ranger/commands.py`

```
from __future__ import (absolute_import, division, print_function)
from ranger.api.commands import Command
from PIL import Image
import os
import errno

class set_wallpaper(Command):
    """:set_wallpaper <filename>

    set the system bg
    """

    def execute(self):
        # 如果选中多个文件，只使用第一个文件设置壁纸
        # If multiple files are selected, only the first file is used to set the wallpaper
        target_filename = self.fm.thistab.get_selection()[0].path if len(self.fm.thistab.get_selection()) > 0 else None
        if not target_filename:
            # 获取当前文件的路径
            # Gets the path to the current file
            target_filename = self.fm.thisfile.path
         
        try:
            with Image.open(target_filename) as img:
                # 解码图像文件并检查文件格式是否正确
                img.verify()
        except (IOError, OSError) as e:
            if e.errno == errno.ENOENT:
                self.fm.notify("The given file does not exist!", bad=True)
            else:
                self.fm.notify(f"Selected file {os.path.basename(target_filename)} is not an image.", bad=True)
            return

        self.fm.notify("run commad: set_wallpaper " + target_filename)
        # 调用外部脚本程序
        # Call an external script program
        #self.fm.run('~/.bscripts/wallset ' + target_filename)
        self.fm.run('ln -sf ' + target_filename + ' ~/.config/rice_assets/Images/wallpaper.png')
        self.fm.run('bspc wm -r')
```
Add the key in `~/.config/ranger/rc.conf`
```
#map xw set_wallpaper
map xw set_wallpaper --fzf-select
map xW set_wallpaper --choosefile --fzf-select
```

**Comment by awarewen** [comment] 2023-02-28 14:49
Also found a strange problem with the 'BSPC WM-R' command, where frequent calls to restart the W M command randomly generate blank window occupancy. 

I tried the 'picom.conf`  has added ' bspc config hide none' (put it on top line ) to hide these blank windows.
 I'm not sure if this will work. 

But please let me know if you have any information about this situation. Thanks


![image](https://user-images.githubusercontent.com/53365857/221887984-3bed881a-8841-492a-8d4f-736a3d185db2.png)

When this happens and you need to restart the window a few more times (possibly at random) , the window will automatically disappear.

**Comment by ikz87** [comment] 2023-02-28 18:25
Yeah that's an issue I've encountered myself. For the longest time I had no idea as to what may be causing it, but now I think it might be eww's fault. The problem is, I haven't been able to reproduce it in literal months now. Will open a new issue for that now since I just thought it had magically fixed itself. Closing this one now

**Closed as completed by ikz87** 2023-02-28 18:25 UTC

**Comment by ikz87** [comment] 2023-02-28 18:53
Just opened #36 to keep track of the blank window problem
